/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/(auth)/sign-in': RouteRecordInfo<'/(auth)/sign-in', '/sign-in', Record<never, never>, Record<never, never>>,
    '/(auth)/sign-up': RouteRecordInfo<'/(auth)/sign-up', '/sign-up', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/budgets/(budgets)': RouteRecordInfo<'/budgets/(budgets)', '/budgets', Record<never, never>, Record<never, never>>,
    '/pots/(pots)': RouteRecordInfo<'/pots/(pots)', '/pots', Record<never, never>, Record<never, never>>,
    '/README': RouteRecordInfo<'/README', '/README', Record<never, never>, Record<never, never>>,
    '/recurring-bills/(recurring-bills)': RouteRecordInfo<'/recurring-bills/(recurring-bills)', '/recurring-bills', Record<never, never>, Record<never, never>>,
    '/transactions/(transactions)': RouteRecordInfo<'/transactions/(transactions)', '/transactions', Record<never, never>, Record<never, never>>,
  }
}
